samchon/openapi

package.json, src/OpenApi.ts, src/OpenApiV3_1.ts, src/internal/OpenApiV3Converter.ts, src/internal/OpenApiV3_1Converter.ts
When `$recursiveRef` comes, convert it to `$ref` in the `OpenApi.convert()` function.
Also fixed `OpenApi.IJsonSchema` union type problem. Have missed to lilst up `ITuple` type.
=> Support `$recursiveRef` of OpenAPI v3.1.

package.json, src/OpenApi.ts, src/OpenApiV3.ts, src/OpenApiV3_1.ts, src/SwaggerV2.ts
Type `integer` of JSON schema means not `int32`, but `int64`. 
Also, the `multipleOf` property must be positive value and it must be greater than zero. The zero value cannot be assigned.
This PR follows such spec of JSON schema, so that upgrade the patch version.
=> Change type limit from `int32` to `int64`.

package.json, src/OpenApi.ts, src/internal/OpenApiV3_1Converter.ts
As `IJsonSchema.IObject.additionalProperties` type is optional, also made `IJsonSchema.ITuple.additionalItems` to be optional for consistency.
=> `IJsonSchema.ITuple.additionalItems` to be optional.

package.json, src/IMigrateDocument.ts, src/IMigrateRoute.ts, src/OpenApi.ts, src/internal/MigrateConverter.ts, src/internal/MigrateRouteAccessor.ts
To support dependent libraries utilizing `@samchon/openapi` which adds special plugin properties starting with `x-` key name, changed `OpenApi.IDocument` and its subsidiary structures to have two generic arguments: `Schema` and `Operation`.
- `OpenApi.IDocument<Schema, Operation>`
- `OpenApi.IOperation<Schema>`
=> Make `OpenApi.IDocument` to be generic.

examples/v3.0/openai.json, package.json, src/OpenApi.ts, src/OpenApiV3.ts, src/OpenApiV3_1.ts, src/SwaggerV2.ts, src/internal/OpenApiV3Converter.ts, src/internal/OpenApiV3Downgrader.ts, src/internal/OpenApiV3_1Converter.ts, src/internal/SwaggerV2Converter.ts, src/internal/SwaggerV2Downgrader.ts
Trying to test OpenAI's swagger document file, I found a bug that current `@samchon/openapi` could not cover `default: null` value case about nullable atomic type case like `type: string` and `type: number`.
This PR fixes the bug, by changing types and converters.
=> Consider nullable typed default null case.

package.json, src/OpenApiV3.ts, src/OpenApiV3_1.ts, src/SwaggerV2.ts, src/internal/OpenApiV3Converter.ts, src/internal/OpenApiV3_1Converter.ts, src/internal/SwaggerV2Converter.ts
It is nonsensible to inserting `null` value to `enum` property array, but Github OpenAPI document is actually doing the crazy thing.
This PR supports it by allowing the `null` value to the `enum` proeprty array.
=> Allow `null` value on `enum` properties.

package.json, src/utils/NamingConvention.ts, src/utils/StringUtil.ts
Looking at github's swagger.json file, reserved keyword like `public`, `private` are used in `OpenApi.IOperation.path` and type name in `OpenApi.IJsonSchema.IReference.$ref`. 
No way at type name, but it would better to avoid the reserved keyword on `IMigrateRoute.accessor` composed by parsing and spitting the `OpenApi.IOperation.path`.
This PR fixes the problem, so that helps OpenAPI generator libraries to be safer.
=> Avoid reserved keyword in `IMigrateRoute.accessor`.

package.json, src/internal/MigrateRouteConverter.ts
When composing `IMigrateRoute.comment` property, if target `OpenApi.IOperation.description` has comment escaping text like `"*/"`, it may break the OpenAPI generator libraries.
This PR solves the problem by escaping such comment breaking text.
=> Avoid comment escaping text.

package.json, rollup.config.js
As same as we configure in `Typia` I would like to add 
- `preserveModules` in rollup config
- `sideEffects: false` in package.json
=> fix build(use preserveModules)

package.json, src/http/HttpMigrateRouteFetcher.ts
In the React Native, it does not support the `File` class.
Instead, it can compose the `FormData` class instance by appending below primitive object type. The primitive type can replace the `File` class instance in the React Native.
In such reason, changed `HttpMigrateRouteFetcher` logic a little bit for the React Native `File` supporting issue.
```typescript
const form: FormData = new FormData();
form.append("key", {
uri: "somewhere-uri-address-of-file-location",
name: "file-name",
type: "content-media-type",
});
```
=> Fix samchon/nestia#1018: `HttpMigrateRouteFetcher` for React Native.

.github/workflows/release.yml
When create a release tag, `npm publish` would be done by Github Actions.
=> Automate npm publish

package.json, src/converters/HttpLlmConverter.ts, src/converters/OpenApiV3Downgrader.ts, src/converters/SwaggerV2Downgrader.ts, test/features/llm/test_llm_schema_nullable.ts, test/features/llm/test_llm_schema_union.ts, test/features/openapi/test_json_schema_downgrade_v20_enum.ts, test/features/openapi/test_json_schema_downgrade_v20_nullable.ts, test/features/openapi/test_json_schema_downgrade_v30_enum.ts, test/features/openapi/test_json_schema_downgrade_v30_nullable.ts
Found some JSON schema downgrade bugs.
When oneOf type is referencing another oneOf type that is caplused in the `components.schema` as named schema, JSON schema downgraders had defined nested `oneOf` type under an `oneOf` type.
This PR fixes the bug, so that below test code works from now on.
```typescript
export const test_llm_schema_union = (): void => {
const components: OpenApi.IComponents = {
schemas: {
named: {
oneOf: [
{
const: 4,
},
{
const: 5,
},
],
},
},
};
const schema: OpenApi.IJsonSchema = {
oneOf: [
{
const: 3,
},
{
$ref: "#/components/schemas/named",
},
],
};
const llm: ILlmSchema | null = HttpLlm.schema({
components,
schema,
});
TestValidator.equals("union")(llm)({
type: "number",
enum: [3, 4, 5],
});
};
```
When `nullable` type is nested in the `$ref` type, JSON schema …
=> Exact JSON schema downgrading.

src/converters/HttpLlmConverter.ts, src/structures/IHttpLlmFunction.ts, src/structures/ILlmFunction.ts, test/controllers/AppController.ts, test/features/llm/test_http_llm_function_tags.ts, test/swagger.json
It would be helpful for indicating the function's category.
=> Add `ILlmFunction.tags` properties for categorization.

package.json, src/HttpLlm.ts, src/converters/HttpLlmConverter.ts, src/structures/IHttpLlmApplication.ts, src/structures/ILlmApplication.ts, src/utils/OpenApiTypeChecker.ts, test/features/llm/test_llm_schema_object.ts, test/features/llm/test_llm_schema_oneof.ts
When recursive type comes in the LLM function calling application schema composer, it had been banned due to `ILlmSchema` does not support the `oneOf` type.
However, this PR makes it possible by supporting a new configurable option, `IHttpLlmApplication.IOptions.recursive`. If you set it to be `false`, the recursive type still be banned. Otherwise you set it to a numeric value, the recursive type would be repeated following the number.
This PR is duplicated with v2 update, but decided to support in the v1.2 update too.
=> Support recursive type in the LLM in v1.

src/converters/HttpLlmConverter.ts, test/controllers/AppController.ts, test/features/llm/test_http_llm_function_deprecated.ts, test/features/llm/test_http_llm_function_multipart.ts, test/features/llm/test_llm_schema_recursive_array.ts, test/swagger.json
This is duplicated with v2 update (#65), but decided to adapt in the v1.2 update too.
=> Ban `multipart/form-data` type in the LLM

examples/function-calling/arguments/claude.additionalProperties.input.json, examples/function-calling/arguments/claude.sale.input.json, examples/function-calling/arguments/llama.additionalProperties.input.json, examples/function-calling/schemas/claude.additionalProperties.schema.json, examples/function-calling/schemas/claude.sale.schema.json, examples/function-calling/schemas/llama.additionalProperties.schema.json, examples/function-calling/schemas/llama.sale.schema.json, package.json, src/converters/ChatGptConverter.ts, src/converters/ClaudeConverter.ts, src/converters/GeminiConverter.ts, src/converters/LlamaConverter.ts, src/converters/LlmConverterV3.ts, src/converters/LlmConverterV3_1.ts, src/converters/LlmSchemaConverter.ts, src/structures/IChatGptSchema.ts, src/structures/IClaudeSchema.ts, src/structures/ILlamaSchema.ts, src/structures/ILlmSchemaV3.ts, src/structures/ILlmSchemaV3_1.ts, src/utils/ChatGptTypeChecker.ts, src/utils/GeminiTypeChecker.ts, src/utils/LlmTypeCheckerV3.ts, src/utils/OpenApiTypeChecker.ts, src/utils/internal/OpenApiTypeCheckerBase.ts, test/features/llm/chatgpt/test_chatgpt_function_calling_default.ts, test/features/llm/claude/test_claude_function_calling_additionalProperties.ts, test/features/llm/llama/test_llama_function_calling_additionalProperties.ts, test/utils/ChatGptFunctionCaller.ts, test/utils/ClaudeFunctionCaller.ts
They are possible to utilize the dynamic key typed object. Therefore, allowed `additionalProperties` in below types. "OpenAI ChatGPT" and "Google Gemini" blocks it.
- `IClaudeSchema`
- `ILlamaSchema`
- `ILlmSchemaV3`
- `ILlmSchemaV3_1`
---------------------
This pull request includes changes to multiple JSON files and schemas to update the structure and remove unnecessary properties. The most significant changes involve adding new input data and modifying the schema definitions to allow additional properties.
* Added new input data in `claude.additionalProperties.input.json` and `llama.additionalProperties.input.json` to include the name, age, and additional properties for a person. [[1]](diffhunk://#diff-16c32d11ef6eddce3d6b427a28ba903399fabe1d4f1b7d837ca20c07e31b22ebR1-R8) …
=> Allow `additionalProperties` in Claude and Llama.

package.json, src/converters/ChatGptConverter.ts, src/converters/GeminiConverter.ts, src/converters/LlmConverterV3_1.ts, test/features/llm/gemini/test_gemini_schema_enum.ts, test/features/llm/gemini/test_gemini_schema_nullable.ts
This pull request includes several changes to the `@samchon/openapi` package, focusing on improving schema validation and adding new test cases for the Gemini converter. The most important changes include updating the package version, enhancing the validation logic in `ChatGptConverter` and `GeminiConverter`, and adding new test cases for schema validation.
* Updated the package version in `package.json` to `2.0.0-dev.20241129-4`.
* [`src/converters/ChatGptConverter.ts`](diffhunk://#diff-53ae686b13f3841defc9fcac8d94ad132673c71ce2a09949b33b248a5cea812fR24): Added a new `validate` function to handle schema validation and updated the existing validation logic to use this function. [[1]](diffhunk://#diff-53ae686b13f3841defc9fcac8d94ad132673c71ce2a09949b33b248a5cea812fR24) …
=> Fix `gemini` schema's `oneOf` detection logic.

package.json, src/converters/LlmSchemaConverter.ts, src/structures/ILlmSchemaV3.ts, src/structures/ILlmSchemaV3_1.ts
This pull request includes several changes to the `@samchon/openapi` package, focusing on updating versioning, modifying configurations, and improving documentation for LLM schema models.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3): Updated the version from `2.0.0-dev.20241130` to `2.0.0-dev.20241130-2`.
* [`src/converters/LlmSchemaConverter.ts`](diffhunk://#diff-c5ee611714455cd0c4c7cce6e365a54713d134c5fd21e86fc3eda642e1687d31L70-R74): Changed the `constraint` property to `true` for both `3.0` and `3.1` configurations in the `DEFAULT_CONFIGS` object.
* [`src/structures/ILlmSchemaV3.ts`](diffhunk://#diff-a83bad0fda93321814c4ce21df194a9e142cf63a291737fbedee22d69536bd42L467-R473): Updated the documentation to reflect the correct …
=> Make `constraint` option to be default `true`

package.json, src/composers/HttpLlmApplicationComposer.ts, src/composers/llm/ChatGptSchemaComposer.ts, src/composers/llm/GeminiSchemaComposer.ts, src/composers/llm/LlmParametersComposer.ts, src/composers/llm/LlmSchemaV3Composer.ts, src/composers/llm/LlmSchemaV3_1Composer.ts, src/typings/IResult.ts, src/utils/internal/OpenApiTypeCheckerBase.ts, test/executable/llama-function-calling.ts, test/features/llm/validate_llm_parameters_separate_array.ts, test/features/llm/validate_llm_parameters_separate_nested.ts, test/features/llm/validate_llm_parameters_separate_object.ts, test/features/llm/validate_llm_parameters_separate_object_additionalProperties.ts, test/features/llm/validate_llm_parameters_separate_ref.ts, test/features/llm/validate_llm_schema_enum.ts, test/features/llm/validate_llm_schema_enum_reference.ts, test/features/llm/validate_llm_schema_nullable.ts, test/features/llm/validate_llm_schema_oneof.ts, test/features/llm/validate_llm_schema_recursive_ref.ts, test/features/llm/validate_llm_schema_reference_description.ts, test/features/llm/validate_llm_schema_separate_string.ts, test/utils/ChatGptFunctionCaller.ts, test/utils/ClaudeFunctionCaller.ts, test/utils/GeminiFunctionCaller.ts, test/utils/LlamaFunctionCaller.ts
This pull request includes a series of changes across multiple files to standardize the usage of the `value` property instead of `data` in result objects. The most important changes involve updates to various schema composers, type definitions, and test files.
* [`src/composers/HttpLlmApplicationComposer.ts`](diffhunk://#diff-f527381cefd42fdd7de3e60a19289402d8ce0f8bf1f64442f5469e84cf68d9ffL108-R108): Changed `result.data` to `result.value` in the return statement.
* [`src/composers/llm/ChatGptSchemaComposer.ts`](diffhunk://#diff-d0c4b1bc6bd6c1280622ba3db00bf102c54ccb57a60d124822ff0d592628d9cfL30-R34): Replaced `result.data` with `result.value` and updated all references accordingly. [[1]](diffhunk://#diff-d0c4b1bc6bd6c1280622ba3db00bf102c54ccb57a60d124822ff0d592628d9cfL30-R34) …
=> Fix `IResult.ISuccess.value`.

README.md
related issue: samchon/typia#1366
This pull request includes a small change to the `README.md` file. The change adds a Discord badge to the list of badges in the file.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R23): Added a Discord badge with a link to the Discord server.
=> Closes samchon/typia#1366: add discord server link

package.json, src/OpenApi.ts, src/composers/HttpLlmApplicationComposer.ts, src/composers/llm/LlmSchemaV3Composer.ts, test/features/llm/test_http_llm_application_human.ts
This pull request introduces several enhancements and fixes, primarily focusing on adding support for human-only operations and improving the handling of additional properties in schemas. The most important changes include updating the package version, adding a new flag for human-only operations, filtering out human-only operations in the application composer, handling additional properties in schema composers, and adding tests for human-only operations.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3): Updated the package version from `2.0.1` to `2.0.2`.
* [`src/OpenApi.ts`](diffhunk://#diff-77f34fd23e2eddbd1b3ebc491255409ecceb4df2c22af81356d4788b4379efbcR444-R453): Added a new flag `x-samchon-human` to indicate human-only …
=> `OpenApi.IOperation["x-samchon-human"]` blocking LLM function composition

package.json, src/composers/llm/LlmSchemaV3Composer.ts, src/composers/llm/LlmSchemaV3_1Composer.ts, test/features/llm/validate_llm_parameters_separate_object_additionalProperties.ts
This pull request includes several changes to the `@samchon/openapi` package and its associated TypeScript files. The changes focus on version updates, improving the handling of additional properties in schemas, and refining test parameters.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3): Updated the package version from `2.0.2` to `2.0.3`.
Schema handling improvements:
* [`src/composers/llm/LlmSchemaV3Composer.ts`](diffhunk://#diff-02fa51db5bda226c48ccb28078266cc34a34d5dab1af1223bd8000ee688cd7b4L222-R230): Added handling for `additionalProperties` in the `llm` and `human` objects, and adjusted the return conditions to account for the presence of `additionalProperties`. …
=> Fix `additionalProperties`' separation problem

package.json, src/composers/llm/ChatGptSchemaComposer.ts, src/composers/llm/LlmSchemaV3Composer.ts, src/composers/llm/LlmSchemaV3_1Composer.ts, test/features/llm/validate_llm_schema_separate_object_empty.ts, test/utils/ChatGptFunctionCaller.ts, test/utils/ClaudeFunctionCaller.ts
This pull request includes several changes to the `@samchon/openapi` package, focusing on schema composition and validation logic. The changes introduce new checks for empty objects and add new test cases to validate these changes.
Schema composition improvements:
* [`src/composers/llm/ChatGptSchemaComposer.ts`](diffhunk://#diff-d0c4b1bc6bd6c1280622ba3db00bf102c54ccb57a60d124822ff0d592628d9cfR263-R269): Added logic to handle empty objects in the `separateParameters` method. [[1]](diffhunk://#diff-d0c4b1bc6bd6c1280622ba3db00bf102c54ccb57a60d124822ff0d592628d9cfR263-R269) [[2]](diffhunk://#diff-d0c4b1bc6bd6c1280622ba3db00bf102c54ccb57a60d124822ff0d592628d9cfR278)
* [`src/composers/llm/LlmSchemaV3Composer.ts`](diffhunk://#diff-02fa51db5bda226c48ccb28078266cc34a34d5dab1af1223bd8000ee688cd7b4R2 …
=> Fix parameters separator for empty object case.

package.json, src/structures/ILlmFunction.ts, test/features/llm/test_llm_merge_parameters.ts, test/utils/LlamaFunctionCaller.ts
It must not be enforced by me, but determined by user.
-------------------------
This pull request includes several updates to the `@samchon/openapi` package, including a version bump, removal of a strict schema type, and additions to test utilities. The most important changes are summarized below:
Version Update:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3): Updated the package version from `2.0.4` to `2.1.0`.
Schema Changes:
* [`src/structures/ILlmFunction.ts`](diffhunk://#diff-25c6cbd1c80f38bb0f80a4a8abbe94cbfa3c66b7e99c4d65ebc41d05f9efc4eeL49-L57): Removed the `strict` property from the `ILlmFunction` interface.
Test Updates:
* [`test/features/llm/test_llm_merge_parameters.ts`](diffhunk://#diff-6daab0cf17e6922b72fcb00feb1297 …
=> Remove `ILlmFunction.strict` property.

README.md, package.json, src/composers/HttpLlmApplicationComposer.ts, src/structures/IHttpLlmFunction.ts, test/examples/chatgpt-function-call-to-sale-create.ts
This pull request includes several changes to the `@samchon/openapi` package, primarily focusing on removing the `strict` property from various files and updating the package version.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L350): Removed the `strict` property from the function call parameters.
* [`src/composers/HttpLlmApplicationComposer.ts`](diffhunk://#diff-f527381cefd42fdd7de3e60a19289402d8ce0f8bf1f64442f5469e84cf68d9ffL193): Removed the `strict` property from the HTTP route configuration.
* [`src/structures/IHttpLlmFunction.ts`](diffhunk://#diff-40aad91cda9d576516527b8ece8e58e9f4ad7779a1c6830cb7d92408fcfa32cbL102-L110): Removed the `strict` property from the `IHttpLlmFunction` interface.
* …
=> Also erase `IHttpLlmFunction.strict` property.

package.json, src/composers/LlmSchemaComposer.ts, src/composers/llm/ChatGptSchemaComposer.ts, src/composers/llm/LlmSchemaV3Composer.ts, src/composers/llm/LlmSchemaV3_1Composer.ts, src/structures/IChatGptSchema.ts, src/structures/ILlmSchemaV3.ts, src/structures/ILlmSchemaV3_1.ts, test/features/llm/chatgpt/test_chatgpt_function_calling_additionalProperties.ts, test/features/llm/chatgpt/test_chatgpt_function_calling_optional.ts, test/features/llm/chatgpt/test_chatgpt_schema_additionalProperties.ts, test/features/llm/chatgpt/test_chatgpt_schema_optional.ts, test/features/llm/claude/test_claude_function_calling_optional.ts, test/features/llm/gemini/test_gemini_function_calling_optional.ts, test/features/llm/llama/test_llama_function_calling_optional.ts, test/features/llm/validate_llm_parameters_separate_object_additionalProperties.ts, test/features/llm/validate_llm_schema_additionalProperties.ts, test/utils/ChatGptFunctionCaller.ts, test/utils/LlamaFunctionCaller.ts
As I've understood that ChatGPT's strict mode is not perfect, and found much better way by giving validation feedback with `typia.validate<T>()` function, I've changed the ChatGPT strict mode to be configurable, and also changed ChatGPT function calling (or structured output) composition strategy.
From now on, ChatGPT schema also supports the optional properties and dynamic key typed object unless the strict mode configured.
> Advised by @AcrylicShrimp
=> Make ChatGPT strict mode configurable.

package.json, src/utils/ChatGptTypeChecker.ts, src/utils/LlmTypeCheckerV3.ts, test/features/llm/validate_llm_type_checker_cover_any.ts, test/features/llm/validate_llm_type_checker_cover_array.ts
`ChatGptTypeChecker` had not considered `additionalProperties` case, and `LlmTypeCheckerV3` had not defined the visitor function.
----------------------
This pull request includes several updates to the `ChatGptTypeChecker` and `LlmTypeCheckerV3` namespaces, as well as adding new test cases for type checker validation. The most important changes include enhancements to the handling of additional properties in schemas, the addition of a new `covers` function in `LlmTypeCheckerV3`, and the creation of new test files for validating type checker coverage.
Enhancements to schema handling:
* [`src/utils/ChatGptTypeChecker.ts`](diffhunk://#diff-02e1720e4962c86045d2f1e706769591dc829b804bc7643a2607c41695d172d4L156-R164): Improved handling of additional properties in schemas by adding checks and …
=> Enhance `ChatGptTypeChecker` and `LlmTypeCheckerV3`.

examples/v3.1/shopping.json, package.json, src/HttpMigration.ts, src/OpenApi.ts, src/composers/HttpLlmApplicationComposer.ts, src/composers/migrate/HttpMigrateApplicationComposer.ts, src/composers/migrate/HttpMigrateRouteAccessor.ts, src/composers/migrate/HttpMigrateRouteComposer.ts, test/features/migrate/test_http_migrate_route_accessor.ts, test/features/migrate/test_http_migrate_route_comment.ts
New plugin properties `OpenApi.IOperation["x-samchon-accessor"]` and `OpenApi.IOperation["x-samchon-controller"]` for OpenAPI generator and LLM application composer, indicating operation's function name and belonged controller.
Also prohibited non-variable function name assignment.
This change would be adjusted to below dependent libraries:
- `typia`
- `@nestia/core`
- `@nestia/editor`
- `@nestia/migrate`
------------------
This pull request includes several changes to the `@samchon/openapi` package, focusing on renaming and refactoring, as well as adding new features to improve the functionality of the package. The most important changes include updating dependencies, renaming files and namespaces, and adding new properties to the OpenAPI document.
* …
=> New plugin property `OpenApi.IOperation["x-samchon-accessor"]`.

package.json, src/composers/HttpLlmApplicationComposer.ts, src/composers/LlmSchemaComposer.ts, src/composers/llm/ChatGptSchemaComposer.ts, src/composers/llm/ClaudeSchemaComposer.ts, src/composers/llm/GeminiSchemaComposer.ts, src/composers/llm/LlamaSchemaComposer.ts, src/composers/llm/LlmSchemaV3Composer.ts, src/composers/llm/LlmSchemaV3_1Composer.ts, test/examples/chatgpt-structured-output.ts, test/features/llm/validate_llm_application_separate.ts
This pull request includes several changes to the codebase to enhance functionality and improve internal handling of schema definitions. The most important changes include version updates, new internal methods, and new test files.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3): Updated the version from `2.3.1` to `2.3.2`.
* [`src/composers/HttpLlmApplicationComposer.ts`](diffhunk://#diff-f527381cefd42fdd7de3e60a19289402d8ce0f8bf1f64442f5469e84cf68d9ffL199-R199): Modified the condition to check if `props.model` has definitions using the new `LlmSchemaComposer.isDefs` method.
* [`src/composers/LlmSchemaComposer.ts`](diffhunk://#diff-058da3c4ceb4aa02b198488eef3b8dd547d7c0f0ee2b2355e1d104527b1d597dR37-R43): Added a new internal …
=> Fix `IHttpLlmFunction.seperated` composing bug.

package.json, src/HttpLlm.ts, src/composers/HttpLlmApplicationComposer.ts, src/structures/IHttpLlmApplication.ts, src/structures/IHttpLlmFunction.ts, src/structures/ILlmFunction.ts, test/features/llm/test_http_llm_application_funtion_name_length.ts
As ChatGPT does not allow 64 length over function name, this PR shorten it.
---------
This pull request includes several changes aimed at improving the functionality and robustness of the `HttpLlm` module. The main changes include adding a new feature to limit the length of function names, updating type definitions, and adding a new test to validate these changes.
**Feature Enhancements:**
* Added a `maxLength` option to limit the length of function names in `HttpLlm` applications. If a function name exceeds this length, it will be truncated or replaced with a UUID if necessary. (`src/HttpLlm.ts`, `src/composers/HttpLlmApplicationComposer.ts`, `src/structures/IHttpLlmApplication.ts`, `src/structures/IHttpLlmFunction.ts`, `src/structures/ILlmFunction.ts`) …
=> `IHttpLlmFunction.name`'s maximum length limit.

package.json, src/utils/AccessorUtil.ts, test/features/issues/test_issue_121_reference_accessor.ts
This pull request includes updates to the `@samchon/openapi` package, improvements to the `AccessorUtil` utility function, and the addition of a new test case for issue 121.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3): Updated the version from `2.3.3` to `2.3.4`.
Improvements to `AccessorUtil`:
* [`src/utils/AccessorUtil.ts`](diffhunk://#diff-d71570a73187c7ea5b8cee3df5ac7decf07bdaa04849d24d67fe968cad8f742aL5-R5): Modified the `reference` function to filter out the first element if it is "#" to avoid incorrect references.
New test case:
* [`test/features/issues/test_issue_121_reference_accessor.ts`](diffhunk://#diff-fa3564f8e5eb97a418271919ed000101cdd9503df4b258731f7392adf8652cb8R1-R26): Added a new test case …
=> Fix #121: accessor bug including `#` symbol.

examples/function-calling/arguments/claude.sale.input.json, examples/function-calling/schemas/claude.sale.schema.json, package.json, src/composers/HttpLlmApplicationComposer.ts, test/features/issues/test_issue_104_upgrade_v20_allOf.ts, test/features/llm/chatgpt/test_chatgpt_function_calling_additionalProperties.ts, test/features/llm/chatgpt/test_chatgpt_function_calling_description_length.ts, test/features/llm/chatgpt/test_chatgpt_function_calling_example.ts, test/features/llm/chatgpt/test_chatgpt_function_calling_name_length.ts, test/features/llm/chatgpt/test_chatgpt_function_calling_optional.ts, test/features/llm/chatgpt/test_chatgpt_function_calling_recursive.ts, test/features/llm/chatgpt/test_chatgpt_function_calling_union.ts, test/features/llm/claude/test_claude_function_calling_additionalProperties.ts, test/features/llm/claude/test_claude_function_calling_default.ts, test/features/llm/claude/test_claude_function_calling_example.ts, test/features/llm/claude/test_claude_function_calling_optional.ts, test/features/llm/claude/test_claude_function_calling_recursive.ts, test/features/llm/claude/test_claude_function_calling_tags.ts, test/features/llm/claude/test_claude_function_calling_union.ts, test/features/llm/gemini/test_gemini_function_calling_default.ts, test/features/llm/gemini/test_gemini_function_calling_example.ts, test/features/llm/gemini/test_gemini_function_calling_optional.ts, test/features/llm/llama/test_llama_function_calling_additionalProperties.ts, test/features/llm/llama/test_llama_function_calling_default.ts, test/features/llm/llama/test_llama_function_calling_example.ts, test/features/llm/llama/test_llama_function_calling_nullable.ts, test/features/llm/llama/test_llama_function_calling_optional.ts, test/features/llm/llama/test_llama_function_calling_recursive.ts, test/features/llm/llama/test_llama_function_calling_tags.ts, test/features/llm/llama/test_llama_function_calling_union.ts
As OpenAI (ChatGPT) does not allow over 1,024 length description property on the tool calling's function definition, `@samchon/openapi` also blocks it on the `IHttpLlmApplication` composing process.
In the same way, `typia.llm.application<App, Model>()` and `typia.llm.applicationOfValidate<App, Model>()` functions will block the 1,024 length over description too.
-----------------
This pull request includes several changes to improve the handling of descriptions and validation in the `HttpLlmApplicationComposer` and related test files, as well as updates to JSON schema files. The most important changes include the addition of description length validation, reordering of JSON schema properties, and updates to test cases.
* [`src/composers/HttpLlmApplicationComposer.ts`](diffhunk://#diff-f52 …
=> Limit `IHttpLlmFunction.description` length under 1,024.

src/composers/llm/ChatGptSchemaComposer.ts, src/composers/llm/ClaudeSchemaComposer.ts, src/composers/llm/GeminiSchemaComposer.ts, src/composers/llm/LlmSchemaV3Composer.ts, src/composers/llm/LlmSchemaV3_1Composer.ts, src/structures/IHttpLlmFunction.ts, src/structures/ILlmFunction.ts, test/features/llm/validate_llm_parameters_separate_array.ts, test/features/llm/validate_llm_parameters_separate_nested.ts, test/features/llm/validate_llm_parameters_separate_object.ts, test/features/llm/validate_llm_parameters_separate_ref.ts, test/features/llm/validate_llm_schema_separate_string.ts
Even though no property exists in the LLM side (properties exist only in the Human side), the `ILlmFunction.ISeparated.llm` property value should be not null for covenience.
This PR enforces the `ILlmFunction.ISeparated.llm` not to be `null`.
=> `ILlmFunction.ISeparated.llm` to be not null.

examples/function-calling/arguments/chatgpt.apple-airpods.input.json, examples/function-calling/arguments/chatgpt.apple-imac.input.json, examples/function-calling/arguments/chatgpt.apple-ipad.input.json, examples/function-calling/arguments/chatgpt.apple-macbook-pro.input.json, examples/function-calling/arguments/chatgpt.apple-magickeyboard.input.json, examples/function-calling/arguments/chatgpt.apple-magicmouse.input.json, examples/function-calling/arguments/chatgpt.apple-vision-pro.input.json, examples/function-calling/arguments/chatgpt.apple-watch.input.json, examples/function-calling/arguments/chatgpt.herman-miller-chair.input.json, examples/function-calling/arguments/chatgpt.leica-m6.input.json, examples/function-calling/arguments/chatgpt.microsoft-surface-pro-9.input.json, examples/function-calling/arguments/chatgpt.samsung-galaxy-watch-7.input.json, examples/function-calling/arguments/chatgpt.stanley-tumbler-collection.input.json, examples/function-calling/prompts/apple-airpods.md, examples/function-calling/prompts/apple-imac.md, examples/function-calling/prompts/apple-ipad.md, examples/function-calling/prompts/apple-iphone.md, examples/function-calling/prompts/apple-magickeyboard.md, examples/function-calling/prompts/apple-magicmouse.md, examples/function-calling/prompts/apple-watch.md
This pull request includes significant updates to the product information for various Apple devices in the `examples/function-calling/arguments` directory. The changes involve adding new product entries and correcting existing ones. 
New product entries:
* [`examples/function-calling/arguments/chatgpt.apple-airpods.input.json`](diffhunk://#diff-c05c8dce0732f661fe3c022e276635579f6778579094da2eeb8ce9896ea969eaR1-R299): Added detailed information about Apple AirPods, including options for different models and colors, stock details, and tags.
* [`examples/function-calling/arguments/chatgpt.apple-imac.input.json`](diffhunk://#diff-60050a21e6b0edf4a79b6b9522ac557c994168ad78cbf5e191a367c9b955a3a4R1-R265): Added detailed information about Apple iMac, including options for different CPU, RAM, and …
=> Fill more function calling examples

package.json, src/composers/llm/ChatGptSchemaComposer.ts, src/utils/internal/OpenApiTypeCheckerBase.ts, test/features/issues/test_issue_127_enum_description.ts
This pull request includes several updates and improvements to the `@samchon/openapi` package, including version updates, bug fixes, and the addition of a new test case.
* Updated the package version from `2.4.0` to `2.4.1` in `package.json`.
* Updated the `typia` dependency version from `7.3.0` to `7.6.0` in `package.json`.
* Modified `ChatGptSchemaComposer` to use `attribute.description` as a fallback if `union[0].description` is undefined.
* Updated `OpenApiTypeCheckerBase` to spread `props.schema` instead of `props`.
* Added a new test case `test_issue_127_enum_description` to verify the description handling in enum schemas.
=> Fix #127: ChatGPT and Gemini schema had dropped enum typed description.

.github/workflows/website.yml, .gitignore, README.md, package.json, typedoc.json, website/public/index.html
This pull request includes several changes to automate the website deployment process and update documentation links. The most important changes include adding a GitHub Actions workflow for website deployment, updating API documentation links in the `README.md` file, and adding TypeDoc configurations and dependencies.
* [`.github/workflows/website.yml`](diffhunk://#diff-c7731b29de71fca225e1dfac88ebe31975a4cd9759ab13e91d86eeadafbddc10R1-R26): Added a new GitHub Actions workflow to automate the deployment of the website on changes to specific files in the `master` branch. The workflow installs dependencies, builds TypeDoc, and deploys to the `gh-pages` branch.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L23-R23): Updated all API …
=> Website publishing

.github/workflows/website.yml, package.json, src/OpenApi.ts, src/index.ts, src/structures/IChatGptSchema.ts, src/structures/IGeminiSchema.ts, src/structures/IJsonSchemaAttribute.ts, src/structures/ILlmSchemaV3.ts, src/structures/ILlmSchemaV3_1.ts
This pull request includes several changes to the `@samchon/openapi` package, focusing on updating the version, improving the schema attributes, and modifying the build process. The most important changes include updating the package version, consolidating schema attributes into a single interface, and updating the build configuration.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3): Updated the package version to `3.0.0-dev.20250211`.
Schema attribute consolidation:
* [`src/structures/IJsonSchemaAttribute.ts`](diffhunk://#diff-e40ad09196e68da5724a1fd81ff44626c8d2d62a79a7e5a536f49d99a3004273R1-R60): Introduced a new `IJsonSchemaAttribute` interface to provide common attributes for JSON schema types.
* …
=> Add `IJsonSchemaAttribute`.

.github/workflows/website.yml, package.json, src/OpenApi.ts, src/OpenApiV3.ts, src/OpenApiV3_1.ts, src/SwaggerV2.ts, src/composers/llm/ChatGptSchemaComposer.ts, src/index.ts, src/structures/IChatGptSchema.ts, src/structures/IClaudeSchema.ts, src/structures/IGeminiSchema.ts, src/structures/IJsonSchemaAttribute.ts, src/structures/ILlmSchemaV3.ts, src/structures/ILlmSchemaV3_1.ts
This pull request includes several changes to the OpenAPI definitions and converters, specifically focusing on the integration of `IJsonSchemaAttribute` and updating the schema attributes. The most important changes include updating various interfaces to extend `IJsonSchemaAttribute`, adding nullable properties, and deprecating old attribute interfaces.
Integration of `IJsonSchemaAttribute`:
* [`src/OpenApi.ts`](diffhunk://#diff-77f34fd23e2eddbd1b3ebc491255409ecceb4df2c22af81356d4788b4379efbcR9): Updated multiple interfaces (e.g., `IConstant`, `IBoolean`, `IInteger`, `INumber`, `IString`, `IArray`, `IObject`, `IReference`, `IOneOf`, `INull`, `IUnknown`) to extend `IJsonSchemaAttribute`. Deprecated `__ISignificant` and `__IAttribute` interfaces. …
=> Enhance IJsonSchemaAttribute type with nested items.

package.json, src/http/HttpMigrateRouteFetcher.ts
This pull request includes a version update and a code improvement in the `HttpMigrateRouteFetcher` module. The most important changes are:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3): Updated the package version from `2.4.2` to `2.4.3`.
* [`src/http/HttpMigrateRouteFetcher.ts`](diffhunk://#diff-e147f1a12a63eec2e3d5a1577f3820cefc0b8c86817f0f573e588df00ab63f48L84-R89): Refactored the path resolution logic in the `_Propagate` function for better readability and maintainability. The variables `path` and `url` were replaced with `resolvedPath` and a more concise URL construction.
=> Fix dangerous URL composition rule.

package.json, rollup.config.js
This pull request includes updates to the build configuration and dependencies to improve the build process.
This needs esm build for typia
Dependency updates:
* Added `tinyglobby` version `^0.2.10` to the `package.json` file.
Build configuration updates:
* Modified `rollup.config.js` to use `tinyglobby` for input file globbing instead of a single entry point.
=> missing esm module build

package.json, src/composers/LlmSchemaComposer.ts, src/composers/llm/ChatGptSchemaComposer.ts, src/composers/llm/ClaudeSchemaComposer.ts, src/composers/llm/GeminiSchemaComposer.ts, src/composers/llm/LlamaSchemaComposer.ts, src/composers/llm/LlmDescriptionInverter.ts, src/composers/llm/LlmSchemaV3Composer.ts, src/composers/llm/LlmSchemaV3_1Composer.ts, src/utils/OpenApiConstraintShifter.ts, test/features/llm/validate_llm_invert_array.ts, test/features/llm/validate_llm_invert_enum.ts, test/features/llm/validate_llm_invert_integer.ts, test/features/llm/validate_llm_invert_nullable.ts, test/features/llm/validate_llm_invert_number.ts, test/features/llm/validate_llm_invert_object.ts, test/features/llm/validate_llm_invert_oneof.ts, test/features/llm/validate_llm_invert_ref.ts, test/features/llm/validate_llm_invert_string.ts
This pull request includes significant updates to the `LlmSchemaComposer` module, including the introduction of inversion functions for various schema composers and the addition of the `LlmDescriptionInverter` utility. These changes enhance the functionality and flexibility of the schema composers by allowing the inversion of schema descriptions.
Key changes include:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3): Updated the version from `2.4.3` to `2.5.0`.
* [`src/composers/LlmSchemaComposer.ts`](diffhunk://#diff-058da3c4ceb4aa02b198488eef3b8dd547d7c0f0ee2b2355e1d104527b1d597dR38-R40): Added an `invert` function and an `INVERTS` constant to support schema inversion. [[1]](diffhunk://#diff-058da3c4ceb4aa02b198488eef3b8dd547d7c0f0 …
=> New function `LlmSchemaComposer.invert()`

package.json, src/composers/llm/ChatGptSchemaComposer.ts, test/features/llm/chatgpt/test_chatgpt_schema_strict.ts
This pull request includes several changes to the `ChatGptSchemaComposer` and introduces a new test for the strict schema validation. The most important changes are the refactoring of the `transform` function to take a configuration object and the addition of a new test file.
Refactoring and improvements to `ChatGptSchemaComposer`:
* [`src/composers/llm/ChatGptSchemaComposer.ts`](diffhunk://#diff-d0c4b1bc6bd6c1280622ba3db00bf102c54ccb57a60d124822ff0d592628d9cfL46-R55): Refactored the `transform` function to accept a configuration object, allowing for more flexible schema transformations. This change affects multiple parts of the file, including how `$defs` and other schema properties are processed. [[1]](diffhunk://#diff-d0c4b1bc6bd6c1280622ba3db00bf102c54ccb57a60d124822ff0d592628d9cfL46-R …
=> Fix ChatGptSchemaComposer's strict mode

package.json, src/composers/llm/ChatGptSchemaComposer.ts, src/composers/llm/ClaudeSchemaComposer.ts, src/composers/llm/LlamaSchemaComposer.ts, src/composers/llm/LlmSchemaV3_1Composer.ts, src/utils/NamingConvention.ts
This pull request includes several changes to the `ChatGptSchemaComposer`, `ClaudeSchemaComposer`, `LlamaSchemaComposer`, and `LlmSchemaV3_1Composer` files, as well as updates to the `NamingConvention` utility. The main focus of these changes is the addition of a `convention` parameter to various functions to handle naming conventions more effectively.
Key changes include:
* Added `NamingConvention` import to `ChatGptSchemaComposer`, `LlamaSchemaComposer`, and `LlmSchemaV3_1Composer` files to handle naming conventions. [[1]](diffhunk://#diff-d0c4b1bc6bd6c1280622ba3db00bf102c54ccb57a60d124822ff0d592628d9cfR9) [[2]](diffhunk://#diff-77518819d0e39da5042e7d25b6345cea620bf8c2f3c181f2bee598b499334881R7)
* Added an optional `convention` parameter to the `separateParameters` function in …
=> `ChatGptSchemaComposer.separateParameters` added new property `convention`

test/benchmark/validate.ts, test/examples/chatgpt-function-call-to-sale-create.ts, test/utils/ChatGptFunctionCaller.ts
This pull request introduces several changes to enhance the testing and validation process for ChatGPT function calls and shopping sale prompts. The key changes include the addition of a new benchmark validation script, updates to the `ChatGptFunctionCaller` utility, and minor corrections in existing test scripts.
* **New benchmark validation script:**
- Added a new script `test/benchmark/validate.ts` to perform multiple trials of ChatGPT function calls and log the results. This script includes asynchronous handling of parameters and completions, as well as optional file writing for schema outputs.
* **Updates to `ChatGptFunctionCaller` utility:**
- Introduced optional `counter` and `model` properties in the `IProps` interface to track the number of attempts and specify the model used for …
=> Experiment of `ISboppingSale.ICreate` validation feedback count

src/HttpLlm.ts, src/HttpMigration.ts
This pull request includes changes to support additional OpenAPI and Swagger document versions in the `HttpLlm` and `HttpMigration` modules. The most important changes include updating the document type definitions and modifying the migration application composition process.
Support for additional document versions:
* [`src/HttpLlm.ts`](diffhunk://#diff-0c890635e48b22e4dea1926131f2726dff205a7f9f78cb2e29cdc0ddedecb8c8R3-R5): Added imports for `OpenApiV3`, `OpenApiV3_1`, and `SwaggerV2` to support additional document versions. Updated the `document` type in the `HttpLlm` namespace to include these new types. [[1]](diffhunk://#diff-0c890635e48b22e4dea1926131f2726dff205a7f9f78cb2e29cdc0ddedecb8c8R3-R5) [[2]](diffhunk://#diff-0c890635e48b22e4dea1926131f2726dff205a7f9f78cb2e29cdc0ddedecb8c8L55-R …
=> Make `HttpLlm.application()` function convenient.

test/benchmark/validate.ts, test/utils/ChatGptFunctionCaller.ts
Adds a --strict command line flag for validation tests and passes the strict parameter to the OpenAI function definition when enabled. This allows testing function calls with strict schema validation.
=> feat(test): add strict mode option for function calling

test/benchmark/validate.ts, test/utils/ChatGptFunctionCaller.ts, test/utils/ShoppingSalePrompt.ts
As I wrote in https://github.com/samchon/openapi/issues/157 , the all error I found is just missing properties.
So I fixed the prompt following OpenAI guid (https://platform.openai.com/docs/guides/prompt-engineering#strategy-write-clear-instructions)
Result:
with `gpt-4o`
```
~/g/g/s/openapi master• ❱ pnpm node bin/test/benchmark/validate.js
[
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
1, 1, 1, 1
]
Success rate: 100%
```
note that [strict mode](https://platform.openai.com/docs/guides/function-calling?api-mode=responses#strict-mode) is disabled in …
=> fix prompt in ShoppingSalePrompt.ts and achieved 100% success rate

rollup.config.js
Same as https://github.com/samchon/typia/pull/1547
We need to emit `d.mts` file for esm
=> fix(rollup): emit d.mts

package.json, src/composers/llm/GeminiSchemaComposer.ts, src/composers/llm/LlmSchemaV3Composer.ts, src/composers/llm/LlmSchemaV3_1Composer.ts, test/features/llm/validate_llm_parameters_reference_escaped_description_of_name.ts
This pull request includes several updates to the `@samchon/openapi` package, focusing on schema composition and validation improvements. The changes include version updates, simplification of schema composition logic, and the addition of new test cases for validating escaped descriptions.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3): Updated the version from `3.2.0` to `3.2.1`.
* [`src/composers/llm/GeminiSchemaComposer.ts`](diffhunk://#diff-4e9da1f0bdac90742383f58756d5fe60a9d5de3293d24f67f6015f9e88d54759L33-R36): Simplified the schema composition by removing the spread operator and directly passing `props` to the `schema` function.
* [`src/composers/llm/LlmSchemaV3Composer.ts`](diffhunk://#diff-02fa51db5bda226c48ccb28078266cc3 …
=> Fix `ILlmSchema.IParameters` missing reference descriptions problem

package.json, src/utils/internal/JsonDescriptionUtil.ts
This pull request includes a version update for the `@samchon/openapi` package and a change to the `JsonDescriptionUtil` utility to handle cases where there is no description or parent references.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3): Updated the version of `@samchon/openapi` from `3.2.1` to `3.2.2`.
Enhancements to `JsonDescriptionUtil`:
* [`src/utils/internal/JsonDescriptionUtil.ts`](diffhunk://#diff-1d99bef15c7e17d904357ea02b82dc443b7142f4ad7d87bad6cf928d3cc1b434R27-R28): Added a check to return `undefined` if there is no description and no parent references.
=> Fix zero string length instead of undefined problem

package.json, src/HttpLlm.ts
This pull request includes a version update and an improvement to the configuration handling in the `HttpLlm` namespace. The most important changes are:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3): Updated the version from `3.2.2` to `3.2.3`.
Configuration handling improvement:
* [`src/HttpLlm.ts`](diffhunk://#diff-0c890635e48b22e4dea1926131f2726dff205a7f9f78cb2e29cdc0ddedecb8c8R102-R113): Introduced `defaultConfig` for `ILlmSchema.IConfig<Model>` and modified the options merging logic to use `Object.fromEntries` for cleaner and more readable code.
=> Fix `HttpLlm.application()`'s options problem.

package.json, src/composers/llm/ChatGptSchemaComposer.ts, src/composers/llm/LlmDescriptionInverter.ts, src/composers/llm/LlmSchemaV3Composer.ts, src/composers/llm/LlmSchemaV3_1Composer.ts, test/executable/chatgpt-invert.ts, test/features/llm/validate_llm_schema_invert.ts
This pull request includes several changes primarily aimed at improving the handling of descriptions in the `LlmDescriptionInverter` and adding new test cases for schema inversion. The most important changes include modifying the `LlmDescriptionInverter` methods to handle undefined descriptions, updating the `ChatGptSchemaComposer` and `LlmSchemaV3Composer` to remove unnecessary nullish coalescing operators, and adding test cases for schema inversion.
Improvements to description handling:
* [`src/composers/llm/LlmDescriptionInverter.ts`](diffhunk://#diff-2250914d491874aab2e76c81574afef16dbc703848dc39b4c7a1fb37eab82837L5-R16): Modified the `numeric`, `string`, and `array` methods to handle `undefined` descriptions and added a new `describe` function to filter out tags and trim the …
=> Exact `LlmSchemaComposer.invert()` function.

.github/workflows/release.yml, package.json, pnpm-lock.yaml, src/OpenApi.ts, src/composers/llm/LlmDescriptionInverter.ts, src/converters/OpenApiV3Upgrader.ts, src/converters/OpenApiV3_1Emender.ts, src/converters/SwaggerV2Upgrader.ts, src/structures/ILlmSchemaV3.ts, src/structures/ILlmSchemaV3_1.ts, src/utils/LlmTypeCheckerV3.ts, src/utils/OpenApiConstraintShifter.ts, src/utils/OpenApiExclusiveEmender.ts, src/utils/internal/OpenApiTypeCheckerBase.ts, test/features/issues/test_issue_121_reference_accessor.ts, test/features/llm/gemini/test_gemini_schema_constraint.ts, test/features/llm/validate_llm_application_mismatch.ts, test/features/llm/validate_llm_application_tuple.ts, test/features/llm/validate_llm_application_type.ts, test/features/llm/validate_llm_schema_invert.ts, test/features/openapi/test_json_schema_type_checker_cover_number.ts
Anthropic Claude has banned `boolean` typed `exclusiveMinimum` and `exclusiveMaximum` properties.
So this PR changes them to `number` type to support claude perflectly, and this is a typical major update.
cc @ryoppippi 
-----------------
This pull request includes several changes that update dependencies, modify type definitions, and refactor code for better maintainability. The most important changes include updates to `package.json` dependencies, modifications to the `OpenApi` namespace, and the introduction of the `OpenApiExclusiveEmender` utility.
* Updated `typia` dependency from `^8.0.0` to `^9.0.0-dev.20250405` in `package.json`.
* Changed `build` and `dev` scripts in `package.json` to use `pnpm` instead of `npm`.
* Changed `exclusiveMinimum` and `exclusiveMaximum` properties from …
=> `exclusiveMinimum`/`exclusiveMaximum` as `number` type

package.json, src/OpenApiV3.ts, src/OpenApiV3_1.ts, src/composers/llm/GeminiSchemaComposer.ts, src/converters/OpenApiV3Downgrader.ts, src/converters/OpenApiV3Upgrader.ts, src/converters/OpenApiV3_1Emender.ts, src/converters/SwaggerV2Upgrader.ts
Even though JSON schema's `examples` property must be `Record<string, any>` type, too much people and frameworks are filling the property with array value.
Considering the specification, this PR is not proper, but as industry players are following the specification, I've determined to allow for the compatibility.
=> Polyfill `IJsonSchema.examples`

README.md, src/structures/IMcpLlmController.ts
This pull request introduces significant updates to the `agentica` library documentation and code examples, as well as a type-related enhancement in the `IMcpLlmController` interface. The key changes include a revamped README for improved clarity and accessibility, and a new dependency warning in the TypeScript interface definition.
* **Enhanced README content**: Simplified and clarified the purpose of `agentica`, emphasizing its ease of use for AI agent development with clear examples of supported protocols (TypeScript Class, Swagger/OpenAPI, MCP). Added a motivational section targeting TypeScript and backend developers to highlight their readiness for AI development.
* **Updated code examples**: Introduced `MobileFileSystem` as a TypeScript class example and added a new `vendor` …
=> Add `@ts-ignore` to `@modelcontextprotocol/sdk` type

src/OpenApi.ts, src/structures/IChatGptSchema.ts, src/structures/IClaudeSchema.ts, src/structures/IDeepSeekSchema.ts, src/structures/ILlamaSchema.ts, src/structures/ILlmSchemaV3_1.ts, src/utils/ClaudeTypeChecker.ts, src/utils/DeepSeekTypeChecker.ts, src/utils/LlamaTypeChecker.ts
This pull request refactors type definitions and type checker exports across multiple schema-related files to improve clarity and consistency. The most significant changes include replacing `export import` with `export type` for type definitions, adding detailed documentation for each type, and switching from `export import` to `export const` for type checkers.
* Replaced `export import` with `export type` for type definitions in `IClaudeSchema`, `IDeepSeekSchema`, and `ILlamaSchema` to better align with TypeScript conventions. Each type now includes detailed comments explaining its purpose and usage. (`src/structures/IClaudeSchema.ts`: [[1]](diffhunk://#diff-642f4c959248f881106878f7df1590f5bb813cbe4ddbf00d399689f634425f55L81-R158) `src/structures/IDeepSeekSchema.ts`: …
=> Fix #163: avoid `export import` statements for specific bundler reason.

build/post.ts, package.json, pnpm-lock.yaml, src/OpenApi.ts
This pull request introduces a new post-build script, updates dependencies, and makes a minor documentation correction. The most significant changes include the addition of a script to copy type definition files after the build process, updates to `typescript` and other dependencies, and a change in a type reference in the documentation.
* Added a new post-build script in `build/post.ts` to copy type definition files (`IMcpLlmController.d.ts` and `IMcpLlmController.d.mts`) from the `src` directory to the `lib` directory. This script is now invoked as part of the `build` process in `package.json`. [[1]](diffhunk://#diff-cbef0c63c4ad3c0f66893abbc080f041c1f819ecfa94f1ed6676e8370091466eR1-R22) [[2]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R10)
* …
=> Fix #184: mcp type error by post build script

package.json, src/composers/llm/LlmSchemaV3_1Composer.ts, test/src/executable/validate.ts
This pull request introduces updates to the `@samchon/openapi` package, focusing on enhancing schema handling and adding comprehensive test cases. The key changes include a version bump, improvements to schema composition logic, and the addition of a detailed test for schema validation.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3): Updated the package version from `4.3.2` to `4.3.3` to reflect the new changes.
* [`src/composers/llm/LlmSchemaV3_1Composer.ts`](diffhunk://#diff-77518819d0e39da5042e7d25b6345cea620bf8c2f3c181f2bee598b499334881L643-R648): Enhanced the schema composition logic by adding support for `oneOf` schemas in the `LlmSchemaV3_1Composer` class. This ensures proper handling of schemas with multiple possible …
=> Fix `ClaudeSchemaComposer.invert()` function bug for `oneOf` type.

package.json, src/composers/llm/ChatGptSchemaComposer.ts, src/composers/llm/LlmSchemaV3_1Composer.ts, src/http/HttpError.ts, src/structures/IChatGptSchema.ts, test/src/features/llm/chatgpt/test_chatgpt_schema_discriminator.ts, test/src/features/llm/schema/validate_llm_schema_discriminator.ts, test/src/features/mcp/validate_mcp_application.ts
This pull request introduces enhancements to several parts of the codebase, including version updates, improved error handling, and support for discriminators in schemas. The most notable changes are the introduction of detailed HTTP error handling, updates to schema composition for ChatGPT, and the addition of discriminator support in the `IChatGptSchema` structure.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3): Updated the package version from `4.3.3` to `4.4.0-dev.20250704`. This likely indicates a development version with new features or improvements.
* [`src/http/HttpError.ts`](diffhunk://#diff-0f71a1ab47f8fd33375f1493d0abd238a1bf4233a1cf7dd500679deea361c453L2-R78): Enhanced the `HttpError` class to include detailed …
=> New AI function calling schema property: `IChatGptSchema.IAnyOf["x-discriminator"]`

src/structures/IValidation.ts, src/utils/OpenApiValidator.ts
This pull request enhances the validation error reporting in `IValidation` and updates related functionality in `OpenApiValidator`. The changes aim to provide more comprehensive context for AI-driven validation processes by introducing a new optional `description` field and refining existing error attributes.
* [`src/structures/IValidation.ts`](diffhunk://#diff-6d81ea249807cc3951be451c0b94f3518dbf8a6c67a4defba6bd9b939126e4dcL105-R170): Added an optional `description` field to the `IError` interface for human-readable explanations of validation errors. Updated the `path` and `expected` attributes to use more precise and standardized formats, improving clarity and compatibility for AI function calling scenarios.
* [`src/utils/OpenApiValidator.ts`](diffhunk://#diff-fcb2482cc0ca0ebdef44a09f132 …
=> Add new property `IValidation.IError.description`

package.json, pnpm-lock.yaml, src/composers/llm/GeminiSchemaComposer.ts, test/package.json
```txt
Some description.
@title some title
```
Also, this strategy would be adjusted to the `typia` too. `typia` will no more define `IJsonSchema.title` from description comment. It will compose `IJsonSchema.title` only by `@title` tag.
```typescript
export interface Something {
/**
* The first line is not title.
*/
first: string;
/**
* The title only comes from JSDocTag like below.
*
* @title this is the title
*/
second: number;
}
```
=> `IChatGptSchema.title` in description as JSDocTag.

src/HttpLlm.ts, src/composers/llm/ChatGptSchemaComposer.ts, src/composers/llm/LlmSchemaV3_1Composer.ts, test/src/features/llm/application/validate_llm_applicationEquals.ts, test/src/features/llm/application/validate_llm_application_separateEquals.ts
This pull request introduces enhancements to LLM schema composition and validation, focusing on new functionality for handling "equals" and "separate" options in the schema configuration. Additionally, it includes comprehensive test cases to validate these features for various models.
* [`src/HttpLlm.ts`](diffhunk://#diff-0c890635e48b22e4dea1926131f2726dff205a7f9f78cb2e29cdc0ddedecb8c8R111): Added support for the `equals` option in the `HttpLlm.application` method to enable stricter validation of schema equality.
* `src/composers/llm/ChatGptSchemaComposer.ts` and `src/composers/llm/LlmSchemaV3_1Composer.ts`: Enhanced `$defs` handling by conditionally assigning `llm` and `human` schema definitions when they are not null. [[1]](diffhunk://#diff-d0c4b1bc6bd6c1280622ba3db00bf102c54ccb57a60d124 …
=> Fix `HttpLlm.application()`'s reference separation problem.

src/structures/ILlmApplication.ts
This pull request updates the `IValidationHook` type in `ILlmApplication.ts` to improve type safety for validation hooks. The main change reverses the type parameter in the validation function to ensure the input is correctly typed as `unknown` and the validation result matches the expected argument type.
Type safety improvement:
* Updated the `IValidationHook` type so that validation functions now accept an input of type `unknown` and return an `IValidation` of the expected argument type, rather than the reverse. This ensures more robust and predictable type checking for validation hooks.
=> Fix `ILlmApplication.IValidationHook` type
